---
name: LWP-UserAgent-ProxyHopper-Base
version: 0.002
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: base class for LWP::UserAgent based modules which want to proxy-hop their requests
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  Class::Data::Accessor: 0.04001
  Devel::TakeHashArgs: 0.001
  List::MoreUtils: 0.21
  WWW::FreeProxyListsCom: 0.002
  WWW::Proxy4FreeCom: 0.001
build_requires:
  Test::More: 0
provides:
  LWP::UserAgent::ProxyHopper::Base:
    file: lib/LWP/UserAgent/ProxyHopper/Base.pm
    version: 0.002
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
